### ISSUE TITLE
Unavailability of Landsat on-demand products due to U.S. government shutdown

### ISSUE THREAD

**Issue by Matiasedguzman** [16EAGLE/getSpatialData#15]
Hi,

I have a problem when I run getLandsat_query in R. I get the next lines after run it:

>Searching USGS EarthExplorer for available products...
>Reading meta data of search results from USGS EarthExplorer...
>Recieving available product levels from USGS-EROS ESPA...
>Error in gSD.get(url = paste0(getOption("gSD.api")$espa, "available-products/",  : 
>Moved Permanently (HTTP 301). Failed to connect to server.._

I saw that USGS-EROS ESPA server is on maintenance, is that the answer of this error? 

Greetings and thank you!

**Comment by 16EAGLE** [comment]
Thanks for reporting and sorry for the delayed reply. Unfortunately, ESPA is currently unavailable due to the temporary shutdown of the United States federal government. This is the reason for both the query failure and the `maintenance` status. See https://espa.cr.usgs.gov/

I just updated `getSpatialData` so that `getLandsat_query` is not failing, if ESPA is unavailable. Instead, the record field `levels_available` is set to `NA`. Please install the newest version and let me know, if the issue could be solved.

**Comment by Matiasedguzman** [comment]
Thank you very much for your answer!  Do you know if ESPA's server will return to be available soon? or it's the first time that this happened?

**Comment by Matiasedguzman** [comment]
In this case, it's possible to change the server for obtaind Landsat 8 data with getLandsat_query?

**Comment by Matiasedguzman** [comment]
do you know another way to get Landsat 8 data in R?

**Comment by 16EAGLE** [comment]
Yes, you can still download Landsat 8 Level 1 data via AWS using `getLandsat_data`. Since ESPA is not available, on-demand processing of higher-level products such as surface reflectances is not possible. This is something that has not to do with `getSpatialData` and will apply for all ESPA clients in R.

I added another change that makes it possible to still download Landsat level 1 data if ESPA is offline. Please reinstall `getSpatialData`.

You can download Landsat 8 data as shown in this example (to be run after setting your AOI, login, archive directory etc.):
```R
records <- getLandsat_query(time_range = c("2018-08-01", "2018-08-31"), name = "LANDSAT_8_C1")
getLandsat_data(records[1,], level = "l1") #to download the first dataset from AWS
```
