### ISSUE TITLE
Error: 'records$uuid' needs to be of type 'character'

### ISSUE THREAD

**Issue by eartherin** [16EAGLE/getSpatialData#18]
getSentinel_data() was running overnight, and it failed sometime during download of the sixth record (the first 5 records appear to have downloaded correctly). After restarting the process at record 7
```datasets <- getSentinel_data(records = records_filtered[7])```  it returns the following ```Error: 'records$uuid' needs to be of type 'character'```. ```class(records_filtered$uuid)``` returns ```"character" ```. I tried getSentinel_data() on various indices and all return the same error. I have restarted R and re-installed getSpatialData with the same result. Running R 3.5.2 on Windows 10.

**Comment by 16EAGLE** [comment]
I do not know why it failed in the first place (maybe some server issues), but if you want to just download the 7th record, you would need to put `,` behind `7`, since you are indexing a `data.frame` row: 
```R
datasets <- getSentinel_data(records = records_filtered[7,])`
```
That is most likely the reason why the record's UUID could not be read. Does this solution work for you?

**Comment by 16EAGLE** [comment]
> That was in relation to a change made back in 2017, but I wonder if some updates were made to the server while I was downloading my records which would have impacted the UUID record?

I am not sure about the cause, but the behavior you are describing indicates that this could have been the case. Since `getSentinel_data` just uses the `url` field for assembling the download request, this meant that the URL would have changed. Just out of interest, did you possibly save both the records of your unsuccessful and your successful requests?
