### ISSUE TITLE
Add number of the current downloading scene

### ISSUE THREAD

**Issue by kadyb** [16EAGLE/getSpatialData#25]
It would be nice if you could see in the console the number of the current downloading scene and the number of all scenes, i. e. `paste0("Downloading scene ", iterator " of ", length(records), "."`.

**Comment by 16EAGLE** [comment]
Great suggestion, thanks. Added this feature with the latest commit. Current download number vs. total download number is displayed for every download at the beginning of the line in the console output, e.g.:
`[1/3] Attempting to download 'MOD09GQ.A2017213.h18v03.006.2017215044107.hdf' to '/MOD09GQ.A2017213.h18v03.006.2017215044107/MOD09GQ.A2017213.h18v03.006.2017215044107.hdf'...`

**Comment by kadyb** [comment]
Thanks, this is really helpful. Don't you think that putting a number next to the word 'attempting' can be confusing? In the sense that it can be understand as the number of attempts to download, not the number of all scenes.

**Comment by 16EAGLE** [comment]
That's true, could be confusing. My intent was to keep the overall message as short as possible:  "Attempting to" is used since there is the possibility that the download fails and therefore will be retried shortly after. Nonetheless, it would be maybe the best to remove "Attempting to" and just replace it with "Downloading" (short, but still much information), what do you think?

`[1/3] Downloading 'MOD09GQ.A2017213.h18v03.006.2017215044107.hdf' to '/MOD09GQ.A2017213.h18v03.006.2017215044107/MOD09GQ.A2017213.h18v03.006.2017215044107.hdf'...`

Or the counter could be changed, e.g. `[Record 1/3] Attempting to download 'X' to 'Y'...` or something like `[Download 1/3] Attempting to download 'X' to 'Y'...`, but that seems redundant.

**Comment by kadyb** [comment]
> it would be maybe the best to remove "Attempting to" and just replace it with "Downloading" (short, but still much information)

I think it will be the best solution. It seems to me that the user doesn't need immediate information that the attempt has failed and another will be taken.

Here comes another idea (open a new issue?). I don't know what exactly returns function getSentinel_data() (only successfully downloaded scenes or all scenes from getSentinel_query() - should be documented), but maybe should returns data frame with all scenes names and their status (downloaded, failed despite attempts, disconnected from the server)?

**Comment by 16EAGLE** [comment]
The numbers of the currently downloading records and there dataset(s) in case they consist of mutliple have now been added along with generally improved console outputs. Also, all functions now return records (sf) `data.frames` to which additional columns are added depending on the function that was called (e.g. get_data adds the path(s) to the downloaded file(s) as a value in a new column `dataset_file`.
