### ISSUE TITLE
Error in isFALSE(quiet) running getMODIS_query

### ISSUE THREAD

**Issue by nedhorning** [16EAGLE/getSpatialData#30]
I tried running the "Parallelized download of MODIS data" example and when I ran this line: 
records <- getMODIS_query(time_range = time_range, name = grep("MOD09GA", product_names, value = T))

I got this error message: Error in isFALSE(quiet) : could not find function "isFALSE"

I also tried records <- getMODIS_query(time_range = time_range, name = "MODIS_MYD14A1_V6")

and I got the same error message.

**Comment by 16EAGLE** [comment]
Thanks for pointing this out. Which version of `R` are you running? `isFALSE` has been introduced with `R` 3.5 which is why `getSpatialData` is not working with any version older than that. Are you using a machine where you could easily update `R`? 

I will add `isFALSE` as a native function to `getSpatialData` to make it downward compatible

**Comment by nedhorning** [comment]
I am running 3.4.4 so it looks like it's a version problem. Thanks for the feedback.
